# Generated by Django 5.2.12 on 2026-03-20 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('CPU', 'CPU / Computadora'), ('ESCANER', 'Escáner'), ('MONITOR', 'Monitor'), ('CAJON', 'Cajón de Dinero'), ('IMPRESORA', 'Impresora'), ('OTRO', 'Componente / Otro')], default='CPU', max_length=20, verbose_name='Tipo de Artículo')),
                ('equipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100, verbose_name='Serie Principal')),
                ('serie_remplazo', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnostico', models.TextField()),
                ('estatus', models.CharField(max_length=50)),
                ('fuente', models.BooleanField(default=False, verbose_name='Fuente')),
                ('ventilador', models.BooleanField(default=False, verbose_name='Ventilador')),
                ('ssd', models.BooleanField(default=False, verbose_name='SSD')),
                ('extensor', models.BooleanField(default=False, verbose_name='Extensor')),
                ('gabinete', models.BooleanField(default=False, verbose_name='Gabinete')),
                ('disipador', models.BooleanField(default=False, verbose_name='Disipador')),
                ('mb', models.BooleanField(default=False, verbose_name='MB')),
                ('memoria_ram', models.BooleanField(default=False, verbose_name='Memoria RAM')),
                ('adaptador_red', models.BooleanField(default=False, verbose_name='Adaptador Red')),
                ('n_serie_fuente', models.CharField(blank=True, max_length=100)),
                ('n_serie_mb', models.CharField(blank=True, max_length=100)),
                ('n_serie_ram', models.CharField(blank=True, max_length=100)),
                ('n_serie_ssd', models.CharField(blank=True, max_length=100)),
                ('n_serie_gabinete', models.CharField(blank=True, max_length=100)),
                ('cable_usb', models.BooleanField(default=False, verbose_name='Cable de Datos (USB)')),
                ('base_escaner', models.BooleanField(default=False, verbose_name='Base del Escáner')),
                ('placa_interna', models.BooleanField(default=False, verbose_name='Placa Interna (Hardware)')),
                ('base_monitor', models.BooleanField(default=False, verbose_name='Base del Monitor')),
                ('cable_hdmi', models.BooleanField(default=False, verbose_name='Cable HDMI')),
                ('cable_corriente', models.BooleanField(default=False, verbose_name='Cable de Corriente')),
                ('bandeja_interna', models.BooleanField(default=False, verbose_name='Bandeja Interna')),
                ('llave', models.BooleanField(default=False, verbose_name='Llave')),
                ('cable_cajon', models.BooleanField(default=False, verbose_name='Cable de Cajón')),
                ('navaja', models.BooleanField(default=False, verbose_name='Navaja (Corte)')),
                ('sensor_papel', models.BooleanField(default=False, verbose_name='Sensor de Papel')),
                ('plancha_termica', models.BooleanField(default=False, verbose_name='Plancha Térmica')),
                ('motor', models.BooleanField(default=False, verbose_name='Motor')),
                ('placa', models.BooleanField(default=False, verbose_name='Placa (Motherboard)')),
                ('modulo_boton', models.BooleanField(default=False, verbose_name='Módulo de Botones')),
                ('inge', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo / Periférico',
                'verbose_name_plural': '2. Inventario (CPUs y Periféricos)',
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia_rastreo', models.CharField(max_length=100, verbose_name='Guía de Paquetería o Folio Interno')),
                ('proyecto', models.CharField(max_length=100, verbose_name='Proyecto Asignado')),
                ('origen', models.CharField(blank=True, max_length=100, verbose_name='Origen / Proveedor (Ej. IBM, Irium)')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de Recepción')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recepción (Guía/Caja)',
                'verbose_name_plural': '1. Recepciones (Entradas)',
            },
        ),
        migrations.CreateModel(
            name='EquipoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='equipos_evidencias/%Y/%m/%d/', verbose_name='Fotografía de Evidencia')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción opcional')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Evidencia Fotográfica',
                'verbose_name_plural': 'Evidencias Fotográficas',
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio del Envío (Ej. PAL-001)')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino (Ej. Irium, IBM)')),
                ('fecha_envio', models.DateField(verbose_name='Fecha de Envío')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('equipos', models.ManyToManyField(blank=True, related_name='pallets', to='inventario.equipo', verbose_name='Artículos Asignados')),
            ],
            options={
                'verbose_name': 'Pallet de Envío',
                'verbose_name_plural': '3. Pallets de Envío (Salidas)',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='inventario.recepcion', verbose_name='Guía de Entrada / Proyecto'),
        ),
    ]
