# Generated by Django 5.2.11 on 2026-03-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='modulo_boton',
            field=models.BooleanField(default=False, verbose_name='Módulo de Botones'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='motor',
            field=models.BooleanField(default=False, verbose_name='Motor'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='navaja',
            field=models.BooleanField(default=False, verbose_name='Navaja (Corte)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='placa',
            field=models.BooleanField(default=False, verbose_name='Placa (Motherboard)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='plancha_termica',
            field=models.BooleanField(default=False, verbose_name='Plancha Térmica'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sensor_papel',
            field=models.BooleanField(default=False, verbose_name='Sensor de Papel'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_item',
            field=models.CharField(choices=[('CPU', 'CPU / Computadora'), ('ESCANER', 'Escáner'), ('MONITOR', 'Monitor'), ('CAJON', 'Cajón de Dinero'), ('IMPRESORA', 'Impresora'), ('OTRO', 'Componente / Otro')], default='CPU', max_length=20, verbose_name='Tipo de Artículo'),
        ),
    ]
