# Generated by Django 5.2.11 on 2026-03-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_equipo_modulo_boton_equipo_motor_equipo_navaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='guia_rastreo',
            field=models.CharField(max_length=100, verbose_name='Guía de Paquetería o Folio Interno'),
        ),
    ]
